language: python
sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

env:
  - DJANGO_VERSION="Django==1.9.*"
  - DJANGO_VERSION="Django==1.10.*"
  - DJANGO_VERSION="Django==1.11.*"
  - DJANGO_VERSION="Django==2.0.*"
  - DJANGO_VERSION="Django==2.1.*"
  - DJANGO_VERSION="Django==2.2.*"

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO_VERSION="Django==2.0.*"
    - python: "2.7"
      env: DJANGO_VERSION="Django==2.1.*"
    - python: "2.7"
      env: DJANGO_VERSION="Django==2.2.*"

install:
  - pip install -q $DJANGO_VERSION
  - pip install flake8

script:
  - flake8 --ignore=E501,W391 rpc4django
  - ./runtravis.py
